/// Flutter icons DefiaazIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DefiaazIcon
///      fonts:
///       - asset: fonts/DefiaazIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DefiaazIcon {
  DefiaazIcon._();

  static const _kFontFam = 'DefiaazIcon';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noti = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
